spring:
  application:
    name: apareamiento-composer
  cloud:
    gateway:
      routes:
        - id: cruces
          uri: lb://ms-cruces
          predicates:
            - Path=/cruces/**

        - id: genealogia
          uri: lb://ms-genealogia
          predicates:
            - Path=/genealogias/**

        - id: optimizacion-cruces
          uri: lb://ms-optimizacion-cruces
          predicates:
            - Path=/optimizaciones/**

        - id: planificacion-cruces
          uri: lb://ms-planificacion-cruces
          predicates:
            - Path=/planificaciones/**

        - id: partos
          uri: lb://ms-partos
          predicates:
            - Path=/partos/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
              
server:
  port: ${SERVER_PORT_APAREAMIENTO_COMPOSER}

eureka:
  instance:
    preferIpAddress: false
    hostname: apareamiento-composer
    instance-id: apareamiento-composer

# App metadata
info:
  app:
    name: Apareamiento Composer
    description: El "Apareamiento Composer" en Rancho Smart orquesta la comunicación entre microservicios para gestionar y consolidar datos relacionados con el apareamiento y la genética del ganado, optimizando los procesos de selección y cría.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}