spring:
  application:
    name: finanzas-composer
  cloud:
    gateway:
      routes:
        - id: contabilidad
          uri: lb://ms-contabilidad
          predicates:
            - Path=/contabilidad/**
            
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
server:
  port: ${SERVER_PORT_FINANZAS_COMPOSER}

eureka:
  instance:
    preferIpAddress: false
    hostname: finanzas-composer
    instance-id: finanzas-composer

# App metadata
info:
  app:
    name: Finanzas Composer
    description: El "Finanzas Composer" en Rancho Smart integra y gestiona la información financiera, orquestando datos sobre gastos, ingresos y presupuestos, para proporcionar una visión completa y optimizada de la salud financiera de las operaciones ganaderas.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}