spring:
  application:
    name: integracion-composer
  cloud:
    gateway:
      routes:
        - id: conexiones-externas
          uri: lb://ms-conexiones-externas
          predicates:
            - Path=/conexiones-externas/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          
server:
  port: ${SERVER_PORT_INTEGRACION_COMPOSER}

eureka:
  instance:
    preferIpAddress: false
    hostname: integracion-composer
    instance-id: integracion-composer

# App metadata
info:
  app:
    name: Integracion Composer
    description: El "Integración Composer" en Rancho Smart coordina la comunicación con sistemas externos, facilitando el intercambio de datos y la interoperabilidad, lo que permite integrar de manera efectiva diversas plataformas y servicios en la gestión ganadera.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}