spring:
  application:
    name: personal-composer
  cloud:
    gateway:
      routes:
        - id: usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/usuarios/**

        - id: credenciales
          uri: lb://ms-credenciales
          predicates:
            - Path=/credenciales/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          
server:
  port: ${SERVER_PORT_PERSONAL_COMPOSER}

eureka:
  instance:
    preferIpAddress: false
    hostname: personal-composer
    instance-id: personal-composer

# App metadata
info:
  app:
    name: Personal Composer
    description: El "Personal Composer" en Rancho Smart coordina la gesti贸n de datos relacionados con el personal, facilitando la integraci贸n de informaci贸n sobre empleados, roles y responsabilidades para optimizar la administraci贸n de recursos humanos en las fincas.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}