spring:
  application:
    name: produccion-composer
  cloud:
    gateway:
      routes:
        - id: alimentacion-suplementos
          uri: lb://ms-alimentacion-suplementos
          predicates:
            - Path=/registros-alimentacion/**

        - id: control-calidad
          uri: lb://ms-control-calidad
          predicates:
            - Path=/calidades-carne/**, /calidades-leche/**

        - id: produccion-carne
          uri: lb://ms-produccion-carne
          predicates:
            - Path=/producciones-carne/**

        - id: produccion-leche
          uri: lb://ms-produccion-leche
          predicates:
            - Path=/producciones-leche/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          
server:
  port: ${SERVER_PORT_PRODUCCION_COMPOSER}

eureka:
  instance:
    preferIpAddress: false
    hostname: produccion-composer
    instance-id: produccion-composer

# App metadata
info:
  app:
    name: Produccion Composer
    description: El "Producción Composer" en Rancho Smart orquesta la comunicación entre los microservicios relacionados con la producción ganadera. Recopila datos de diferentes servicios, como inventario y producción, para construir respuestas completas y optimizar la gestión productiva.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}