spring:
  application:
    name: salud-composer

server:
  port: ${SERVER_PORT_SALUD_COMPOSER}


# App metadata
info:
  app:
    name: Salud Composer
    description: El "Salud Composer" en Rancho Smart coordina la interacci贸n entre microservicios para reunir y procesar informaci贸n relacionada con la salud del ganado, proporcionando una visi贸n consolidada para la gesti贸n y monitoreo de los animales.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}