spring:
  application:
    name: salud-composer
  cloud:
    gateway:
      routes:
        - id: consultas
          uri: lb://ms-consultas
          predicates:
            - Path=/consulta/**

        - id: historial-medico
          uri: lb://ms-historial-medico
          predicates:
            - Path=/historial-medico/**

        - id: procedimientos-medicos
          uri: lb://ms-procedimientos-medicos
          predicates:
            - Path=/procedimiento-medico/**

        - id: tratamientos
          uri: lb://ms-tratamientos
          predicates:
            - Path=/tratamiento/**

        - id: vacunas
          uri: lb://ms-vacunas
          predicates:
            - Path=/vacuna/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          
server:
  port: ${SERVER_PORT_SALUD_COMPOSER}

eureka:
  instance:
    preferIpAddress: false
    hostname: salud-composer
    instance-id: salud-composer

# App metadata
info:
  app:
    name: Salud Composer
    description: El "Salud Composer" en Rancho Smart coordina la interacci贸n entre microservicios para reunir y procesar informaci贸n relacionada con la salud del ganado, proporcionando una visi贸n consolidada para la gesti贸n y monitoreo de los animales.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}