spring:
  application:
    name: ventas-composer
  cloud:
    gateway:
      routes:
        - id: clientes
          uri: lb://ms-clientes
          predicates:
            - Path=/clientes/**

        - id: inventario-ventas
          uri: lb://ms-inventario-ventas
          predicates:
            - Path=/animales-venta/**

        - id: mercado
          uri: lb://ms-mercado
          predicates:
            - Path=/mercado/**

        - id: ventas
          uri: lb://ms-ventas
          predicates:
            - Path=/ventas/**, /ventas-produccion/** 

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
                      
server:
  port: ${SERVER_PORT_VENTAS_COMPOSER}

eureka:
  instance:
    preferIpAddress: false
    hostname: ventas-composer
    instance-id: ventas-composer

# App metadata
info:
  app:
    name: Ventas Composer
    description: El "Ventas Composer" en Rancho Smart coordina la comunicación entre microservicios relacionados con las transacciones y gestiones de venta, facilitando la integración de datos sobre clientes, productos y procesos de venta para optimizar la administración comercial.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}