spring:
  application:
    name: integracion-composer

server:
  port: ${SERVER_PORT_INTEGRACION_COMPOSER}


# App metadata
info:
  app:
    name: Integracion Composer
    description: El "Integración Composer" en Rancho Smart coordina la comunicación con sistemas externos, facilitando el intercambio de datos y la interoperabilidad, lo que permite integrar de manera efectiva diversas plataformas y servicios en la gestión ganadera.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}