spring:
  application:
    name: ms-cruces
  datasource:
      url: ${DB_MS_CRUCES_URL}
  kafka:
    consumer:
      group-id: apareamiento
      properties:
        spring:
          deserializer:
            value:
              json:
                type:
                  mappings:
                    animalDTO: com.rancho_smart.dto.AnimalDTO

server:
  port: ${SERVER_PORT_CRUCES}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-cruces
    instance-id: ms-cruces
# App metadata
info:
  app:
    name: Cruces
    description: Rancho Smart MS Cruces es un microservicio que gestiona la información sobre las cruzas del ganado, registrando detalles sobre apareamientos, resultados y características de las crías, para optimizar la genética y mejorar la producción en la finca.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}