spring:
  application:
    name: ms-credenciales
  datasource:
    url: ${DB_MS_CREDENCIALES_URL}

server:
  port: ${SERVER_PORT_CREDENCIALES}

# App metadata
info:
  app:
    name: Control de Calidad
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}