spring:
  application:
    name: ms-credenciales
  datasource:
    url: ${DB_MS_CREDENCIALES_URL}
  kafka:
    consumer:
      group-id: personal

server:
  port: ${SERVER_PORT_CREDENCIALES}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-credenciales
    instance-id: ms-credenciales
# App metadata
info:
  app:
    name: Control de Calidad
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}