spring:
  application:
    name: ms-historial-medico
  datasource:
    url: ${DB_MS_HISTORIAL_MEDICO_URL}

server:
  port: ${SERVER_PORT_HISTORIAL_MEDICO}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-historial-medico
    instance-id: ms-historial-medico

# App metadata
info:
  app:
    name: Historial Medico
    description: Rancho Smart MS Historial Médico es un microservicio que centraliza y gestiona la información sobre el historial médico del ganado, incluyendo consultas, tratamientos y vacunaciones, permitiendo un seguimiento integral de la salud de los animales.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}