spring:
  application:
    name: ms-infraestructura
  datasource:
    url: ${DB_MS_INFRAESTRUCTURA_URL}
  kafka:
    consumer:
      group-id: infraestructura
      properties:
        spring:
          deserializer:
            value:
              json:
                type:
                  mappings:
                    animalDTO: com.rancho_smart.dto.AnimalDTO

server:
  port: ${SERVER_PORT_INFRAESTRUCTURA}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-infraestructura
    instance-id: ms-infraestructura

# App metadata
info:
  app:
    name: Infraestructura
    description: Rancho Smart MS Infraestructura es un microservicio que gestiona los aspectos relacionados con la infraestructura de la finca, incluyendo el registro de instalaciones, recursos físicos y mantenimiento, asegurando un entorno óptimo para la producción ganadera.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}