spring:
  application:
    name: ms-mercado
  datasource:
    url: ${DB_MS_MERCADO_URL}
  kafka:
    consumer:
      group-id: ventas
      properties:
        spring:
          deserializer:
            value:
              json:
                type:
                  mappings:
                    animalDTO: com.rancho_smart.dto.AnimalDTO

server:
  port: ${SERVER_PORT_MERCADO}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-mercado
    instance-id: ms-mercado

# App metadata
info:
  app:
    name: Mercado
    description: Rancho Smart MS Mercado 
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}