spring:
  application:
    name: ms-produccion-leche
  datasource:
    url: ${DB_MS_PRODUCCION_LECHE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${SERVER_PORT_PRODUCCION_LECHE}


# App metadata
info:
  app:
    name: Producci칩n de Leche
    description: Rancho Smart MS Producci칩n Leche es un microservicio encargado de gestionar la producci칩n de leche en la finca, controlando el rendimiento de las vacas lecheras, la calidad del producto y los registros de orde침o.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}