spring:
  application:
    name: ms-produccion-leche
  datasource:
    url: ${DB_MS_PRODUCCION_LECHE_URL}
  kafka:
    consumer:
      group-id: produccion
      properties:
        spring:
          deserializer:
            value:
              json:
                type:
                  mappings:
                    animalDTO: com.rancho_smart.dto.AnimalDTO
                    
server:
  port: ${SERVER_PORT_PRODUCCION_LECHE}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-produccion-leche
    instance-id: ms-produccion-leche

# App metadata
info:
  app:
    name: Producci칩n de Leche
    description: Rancho Smart MS Producci칩n Leche es un microservicio encargado de gestionar la producci칩n de leche en la finca, controlando el rendimiento de las vacas lecheras, la calidad del producto y los registros de orde침o.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}