spring:
  application:
    name: ventas-composer

server:
  port: ${SERVER_PORT_VENTAS_COMPOSER}


# App metadata
info:
  app:
    name: Ventas Composer
    description: El "Ventas Composer" en Rancho Smart coordina la comunicación entre microservicios relacionados con las transacciones y gestiones de venta, facilitando la integración de datos sobre clientes, productos y procesos de venta para optimizar la administración comercial.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}