spring:
  application:
    name: apareamiento-composer

server:
  port: ${SERVER_PORT_APAREAMIENTO_COMPOSER}


# App metadata
info:
  app:
    name: Apareamiento Composer
    description: El "Apareamiento Composer" en Rancho Smart orquesta la comunicación entre microservicios para gestionar y consolidar datos relacionados con el apareamiento y la genética del ganado, optimizando los procesos de selección y cría.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}