spring:
  application:
    name: ms-alimentos
  datasource:
    url: ${DB_MS_ALIMENTOS_URL}
  kafka:
    consumer:
      group-id: inventario
      
server:
  port: ${SERVER_PORT_ALIMENTOS}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-alimentos
    instance-id: ms-alimentos

# App metadata
info:
  app:
    name: Alimentos
    description: Rancho Smart MS Alimentos es un microservicio que gestiona la informaci贸n sobre los insumos y alimentos del ganado, incluyendo su inventario, calidad y distribuci贸n, para asegurar una nutrici贸n adecuada y optimizar la producci贸n ganadera.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}