spring:
  application:
    name: ms-cruces
  datasource:
    url: ${DB_MS_CRUCES_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${SERVER_PORT_CRUCES}


# App metadata
info:
  app:
    name: Cruces
    description: Rancho Smart MS Cruces es un microservicio que gestiona la información sobre las cruzas del ganado, registrando detalles sobre apareamientos, resultados y características de las crías, para optimizar la genética y mejorar la producción en la finca.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}