spring:
  application:
    name: ms-conexiones-externas
  datasource:
    url: ${DB_MS_CONEXIONES_EXTERNAS_URL}

server:
  port: ${SERVER_PORT_CONEXIONES_EXTERNAS}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-conexiones-externas
    instance-id: ms-conexiones-externas

# App metadata
info:
  app:
    name: Conexiones Externas
    description: Rancho Smart MS Conexiones Externas es un microservicio que facilita la integración y comunicación con sistemas externos, permitiendo el intercambio de datos y asegurando una interoperabilidad fluida con plataformas y servicios externos relacionados con la gestión ganadera.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}