spring:
  application:
    name: ms-produccion-carne
  datasource:
    url: ${DB_MS_PRODUCCION_CARNE_URL}
    
server:
  port: ${SERVER_PORT_PRODUCCION_CARNE}


# App metadata
info:
  app:
    name: Producci贸n de Carne
    description: Rancho Smart MS Producci贸n Carne es un microservicio que gestiona la producci贸n de carne en la finca, incluyendo el seguimiento de animales destinados para este fin, asegurando una operaci贸n eficiente.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}