spring:
  application:
    name: ms-produccion-carne
  datasource:
    url: ${DB_MS_PRODUCCION_CARNE_URL}
  kafka:
    consumer:
      group-id: produccion
      properties:
        spring:
          deserializer:
            value:
              json:
                type:
                  mappings:
                    animalDTO: com.rancho_smart.dto.AnimalDTO
                    
server:
  port: ${SERVER_PORT_PRODUCCION_CARNE}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-produccion-carne
    instance-id: ms-produccion-carne

# App metadata
info:
  app:
    name: Producci贸n de Carne
    description: Rancho Smart MS Producci贸n Carne es un microservicio que gestiona la producci贸n de carne en la finca, incluyendo el seguimiento de animales destinados para este fin, asegurando una operaci贸n eficiente.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}