spring:
  application:
    name: produccion-composer

server:
  port: ${SERVER_PORT_PRODUCCION_COMPOSER}


# App metadata
info:
  app:
    name: Produccion Composer
    description: El "Producción Composer" en Rancho Smart orquesta la comunicación entre los microservicios relacionados con la producción ganadera. Recopila datos de diferentes servicios, como inventario y producción, para construir respuestas completas y optimizar la gestión productiva.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}