spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        enabled: true
        native:
          search-locations:
          - classpath:/config          
  profiles:
    active: native

server:
  port: ${SERVER_PORT_CONFIG}

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# App metadata
info:
  app:
    name: Config Server
    description: El Config Server en Rancho Smart centraliza y gestiona la configuración de los microservicios, permitiendo la actualización dinámica de propiedades y ajustes de manera segura y eficiente en todo el sistema ganadero.
    version: 1.0.0
  company:
    name: Rancho Smart
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}
